name: dslink_vapix
description: Axis DSLink
environment:
    sdk: ">=1.13.0 <2.0.0"
dependencies:
    dslink:
        git: https://github.com/IOT-DSA/sdk-dslink-dart.git
    http: "^0.11.3"
    xml:  "^2.4.3"
    crypto: "2.0.1"
